import { createRequire } from 'module';
const require = createRequire('d:/Code/sugerenciasMun/frontend/');
const { chromium } = require('playwright');
const b = await chromium.launch({ channel: 'msedge' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.on('pageerror', e => console.log('  PAGEERROR:', e.message.slice(0,140)));
p.on('console', m => { if (m.type()==='error') console.log('  CONSOLA:', m.text().slice(0,140)); });
await p.goto('file:///D:/Code/sugerenciasMun/frontend/public/calls/index.html', { waitUntil: 'load' });
await p.waitForTimeout(2000);
console.log('  cierreDe definida:', await p.evaluate(() => typeof cierreDe));
console.log('  CIERRE definido  :', await p.evaluate(() => typeof CIERRE));
await p.click('text=Trabajar').catch(()=>{});
await p.waitForTimeout(1000);
await p.evaluate(() => { for (const n of document.querySelectorAll('.lista-col *')) if (n.onclick || n.tagName==='BUTTON') { n.click(); break; } });
await p.waitForTimeout(1200);
console.log('  ficha abierta    :', await p.evaluate(() => !!document.querySelector('.f-body')));
console.log('  bloque cierre    :', await p.evaluate(() => !!document.querySelector('.cierre-b')));
console.log('  secciones ficha  :', await p.evaluate(() => [...document.querySelectorAll('.f-body .sec label')].map(l=>l.textContent.trim()).join(' | ')));
await b.close();
